chore: use correct version based on latest release
decentraland/catalyst pull request #802
Opened 2021-12-17 16:02 UTC by menduz

2021-12-17 16:13 UTC, jmoguilevsky approved these changes

2021-12-17 20:03 UTC, agusaldasoro commented on .circleci/config.yml
> +              CATALYST_VERSION="$(curl https://api.github.com/repos/decentraland/catalyst/releases/latest -s | jq .name -r)-next"
aren't we in a GitHub repository when running this? If so, then we should use git commands.

Also, if the latest version is `2.5.0` then it happens that `2.5.0-next < 2.5.0` acording semver. We should increase the minor version before adding the `-next`

2021-12-20 17:15 UTC, agusaldasoro requested changes
aren't we in a GitHub repository when running this? If so, then we should use git commands.

Also, if the latest version is 2.5.0 then it happens that 2.5.0-next < 2.5.0 acording semver. We should increase the minor version before adding the -next

2022-01-07 16:53 UTC, closed without merging

2022-01-07 16:59 UTC, guidota commented
`master` branch deleted, reopen with new default branch (`main`)