Fail if not found catalysts in bootstrap
decentraland/catalyst pull request #860
Opened 2022-01-14 14:58 UTC by agusaldasoro

2022-01-14 14:58 UTC, pentreathm approved these changes

2022-01-14 15:00 UTC, menduz requested changes

2022-01-14 15:00 UTC, menduz commented on content/src/service/synchronization/bootstrapFromSnapshots.ts
> +  const catalystServers = await ensureListOfCatalysts(cluster, 20 /* retries */, ms('30s') /* wait time */)
That change will halt the execution for up to 10 minutes. please consider only incrementing the amount of retries.

```suggestion
  const catalystServers = await ensureListOfCatalysts(cluster, 30 /* retries */, 1000 /* every 1sec */)
```

2022-01-18 14:38 UTC, guidota approved these changes

2022-01-18 18:01 UTC, closed without merging